name: CI

on:
  push:
    branches:
        - main

jobs: 
  changed_files:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v38

      - name: Get commit hash
        id: commit-hash
        uses: prompt/actions-commit-hash@v2

      - name: Run common
        env:
          COMMIT_HASH: "${{ steps.commit-hash.outputs.short }}"
          COMMIT_FILES: "${{ steps.changed-files.outputs.all_changed_files }}"
        run: "cd scripts && npm i && cd .. && npx ts-node --esm scripts/common.ts"