name: CI

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs: 
  changed_files:
    runs-on: ubuntu-latest
    name: Build Commit
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v38

      - name: Get commit hash
        id: commit-hash
        uses: prompt/actions-commit-hash@v2
      
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Run common
        id: common
        env:
          COMMIT_HASH: ${{ steps.commit-hash.outputs.short }}
          COMMIT_PATHS: ${{ steps.changed-files.outputs.all_changed_files }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          REPOSITORY: ${{ github.repository }}
        run: "cd scripts && pnpm i && cd .. && npx ts-node --esm scripts/common.ts"

      - name: Upload assets artifact
        if: ${{ !contains(steps.common.outputs.assets, 'false') }}
        uses: actions/upload-artifact@v3
        with:
          name: assets
          path: dist/

      - name: Bump version and push tag
        id: tag_version
        if: ${{ !contains(steps.common.outputs.changelog, 'false') }}
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.ORG_TOKEN }}
          custom_tag: ${{ steps.commit-hash.outputs.short }}

      - name: Release
        if: ${{ !contains(steps.common.outputs.changelog, 'false') }}
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.common.outputs.assets }}
          tag_name: "v${{ steps.commit-hash.outputs.short }}"
          name: ${{ steps.common.outputs.release }}
          body: ${{ steps.common.outputs.changelog }}